###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /public
        volumes:
            - '.:/public'
        environment:
            - MYSQL_ROOT_PASSWORD=adianti
            - MYSQL_DATABASE=adianti
            - MYSQL_USER=adianti
            - MYSQL_PASSWORD=adianti
        ports:
            - '3402:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /public
        volumes:
            - '.:/public'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '3400:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /public
        volumes:
            - '.:/public'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'
